import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import authRoutes from './routes/auth.routes.js';
import masterRoutes from './routes/master.routes.js';
import campaignRoutes from './routes/campaign.routes.js';
import leadRoutes from './routes/lead.routes.js';
import followupRoutes from './routes/followup.routes.js';
import applicationRoutes from './routes/application.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import miscRoutes from './routes/misc.routes.js';
import { errorHandler, notFound } from './middleware/error.middleware.js';
export const app = express();
app.use(helmet());
app.use(cors({ origin: env.frontendUrl, credentials: true }));
app.use(express.json({ limit:'2mb' }));
app.use(cookieParser());
app.use('/api/auth', rateLimit({ windowMs: 5*60*1000, limit: 50 }), authRoutes);
app.use('/api/master', masterRoutes);
app.use('/api/campaigns', campaignRoutes);
app.use('/api/leads', leadRoutes);
app.use('/api/follow-ups', followupRoutes);
app.use('/api/applications', applicationRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api', miscRoutes);
app.get('/health', (_req,res)=>res.json({ ok:true, service:'ilead-api' }));
app.use(notFound); app.use(errorHandler);
