import { Router } from 'express';
import { prisma } from '../config/db.js';
import { requireAuth } from '../middleware/auth.middleware.js';
import { asyncHandler } from '../utils/asyncHandler.js';
const router = Router(); router.use(requireAuth);
router.get('/', asyncHandler(async (_req,res)=>res.json(await prisma.followUp.findMany({take:100,include:{lead:true,staff:true},orderBy:{followUpDate:'desc'}}))));
router.post('/', asyncHandler(async (req,res)=>res.status(201).json(await prisma.followUp.create({data:req.body}))));
router.get('/overdue', asyncHandler(async (_req,res)=>res.json(await prisma.followUp.findMany({where:{nextFollowUpDate:{lt:new Date()}},include:{lead:true,staff:true}}))));
router.get('/lead/:leadId', asyncHandler(async (req,res)=>res.json(await prisma.followUp.findMany({where:{leadId:req.params.leadId},orderBy:{followUpDate:'desc'}}))));
export default router;
